### ISSUE TITLE
No live view for Ximea camera & issue with .mvk file

### ISSUE THREAD

**Issue by AmyCourtney** [fastvideo/gpu-camera-sample#10]
Hello,

Thank you for developing this software! It is exactly what I was looking for- I have been having issues recording 25fps videos with the Ximea software and it looks your your software has solved my problems. 

However, there are two issue I wanted to ask for your help with:

1. I can't see the live feed from the camera. I know the software has access to the camera because I can record videos. The live camera view works fine in the Ximea software. Please let me know what information you need to figure out what could be going wrong here.

![Capture](https://user-images.githubusercontent.com/46894683/134697328-3fa2ecd0-fdda-4f86-b3f7-7452f679d859.PNG)

2. When I save videos with the H.265 codec it saves the file as .mkv however, I haven't been able to open this is VLC (I tried all these fixes https://withwin.in/how-to-fix-vlc-media-player-issues-while-playing-mkv-files/) or in the image analysis software I want to analyse these videos in. Is it possible to save these videos as .avi instead of .mvk using the H.265 codec?

Thank you in advance for your help!

Amy

**Comment by fastvideo** [comment]
Your default exposure setting is 7,000 microseconds which is too low and that's why your screen is black.
Please set exposure to be 40,000 microseconds and you will see a live picture.
As far as concerns video encoding on GPU, this is done via ffmpeg, so you will need to tune your video encoding settings there.

**Comment by KennedyClouds** [comment]
Alternatively, increase the amount of available lighting to allow for shorter exposure times.

**Comment by AmyCourtney** [comment]
Thanks for your suggestions!

The exposure is 7ms which is sufficient in the Ximea software. I also can save videos from your software that do not have a black screen and so I don't think the black screen is caused by this.

Can you point me the direction of where I can find more information about how to tune video encoding settings in ffmpeg?

Thank you!

**Comment by fastvideo** [comment]
This is just a sample application to show how GPU-based image processing could be done for camera streams, so there are many things which are absent here. That application is not focused on full camera control.
XIMEA camera can output 8-bit, 12-bit or 16-bit raw frames, so your default brightness depends on that as well. There are other internal tunings of XIMEA cameras, so you need to initialize camera mode and other settings by yourself.
Please have a look at source codes to see ffmpeg params as well.
