### ISSUE TITLE
jpeg decode speed

### ISSUE THREAD

**Issue by liujiaxi984** [fastvideo/gpu-camera-sample#11]
I am running JpegSample in NVIDIA Jetson Xavier NX. My average decode time is 36.849 ms, but the benchmark in your homepage is JPEG decoder (24-bit, quality 90%, 4:4:4) – 1.37 ms. 

my running command is ./JpegSample -i ~/1080p.jpg -o final.bmp -info -repeat 100

Is this normal? Please help me.

![result pic](https://user-images.githubusercontent.com/23713234/139821745-10c8f206-2c98-407b-b8dd-79fdbf79946d.png)

**Comment by fastvideo** [comment]
1. Please check your power mode. Utility nvpmodel has to been used to change the power mode. Mode with power consumption is MAXN. To activate this mode call  sudo /usr/sbin/nvpmodel –m 0
2. To get fast jpeg decoding, your jpeg image should have built-in restart markers. Without these restart markers high performance jpeg decoding is not possible. Our encoder adds these markers automatically, so please create jpeg image with our encoder and then try to decode it. That should work.
In the software output you can see a number or restart markers in your jpeg image, it should not be 0.

**Comment by qizhouqiqi** [comment]
> I am running JpegSample in NVIDIA Jetson Xavier NX. My average decode time is 36.849 ms, but the benchmark in your homepage is JPEG decoder (24-bit, quality 90%, 4:4:4) – 1.37 ms.
> 
> my running command is ./JpegSample -i ~/1080p.jpg -o final.bmp -info -repeat 100
> 
> Is this normal? Please help me.
> 
> ![result pic](https://user-images.githubusercontent.com/23713234/139821745-10c8f206-2c98-407b-b8dd-79fdbf79946d.png)

I want to know where to download JpegSample in NVIDIA Jetson Xavier NX.
