### ISSUE TITLE
./rc_genicam_api/system.h:39:10: fatal error: GenApi/GenApi.h: No such file or directory

### ISSUE THREAD

**Issue by antortjim** [fastvideo/gpu-camera-sample#12]
Dear fastvideo,

thanks for developing the program!

Specs:

Ubuntu 20.04
CUDA 11.3 / 11.4 (I have both installed and I just need to change the link in `/usr/local/cuda` to either `/usr/local/cuda-11.3` or `/usr/local/cuda-11.4`. 
qtcreator 4.11.0

I have installed pylonviewer 6.2.0.21487, which creates a folder under `/opt/pylon/includes` that brings `GenApi/GenApi.h`. But even though I have added said path to the INCLUDEPATHS variable in my .bashrc (like so):

```
export INCLUDEPATH="/opt/pylon/include/"${INCLUDEPATH:+:${INCLUDEPATH}}
```

the compilation step fails both with qcreator and in the terminal

```
cd CameraSample/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile $HOME/gpu-camera-sample/src/CameraSample/CameraSample.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug ) && /usr/bin/make -f Makefile
```
```
g++ -c -pipe -g -Wall -W -D_REENTRANT -fPIC -DSUPPORT_GENICAM -DGENICAM_NO_AUTO_IMPLIB -DGENTL_INSTALL_PATH='"/opt/XIMEA/lib"' -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I/usr/local/cuda-11/include -I/home/vibflysleep/gpu-camera-sample/OtherLibsLinux/nvcodecs/include -I../../OtherLibsLinux/FastvideoSDK/fastvideo_sdk/inc -I../../OtherLibsLinux/FastvideoSDK -I../../OtherLibsLinux/FastvideoSDK/common -I/home/vibflysleep/gpu-camera-sample/OtherLibsLinux/FastvideoSDK/libs/OpenGL/inc -I/home/vibflysleep/gpu-camera-sample/OtherLibsLinux/ffmpeg/include -I/home/vibflysleep/gpu-camera-sample/OtherLibsLinux/GenICam/library/CPP/include -I../../OtherLibsLinux/FastvideoSDK/core_samples -I. -ICUDASupport -IWidgets -ICamera -IRtspServer -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o MainWindow.o MainWindow.cpp
In file included from Camera/GeniCamCamera.h:7,
                 from MainWindow.cpp:59:
./rc_genicam_api/system.h:39:10: fatal error: GenApi/GenApi.h: No such file or directory
   39 | #include <GenApi/GenApi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:1115: MainWindow.o] Error 1

```

Could you please help me out? Thank you!

**Comment by AlexVRom** [comment]
Gpu-camera-sample uses GenICam headers and libs from GenICamTM Package Version 2019.11, not from Basler SDK.
According to your log compiler expected to find GenApi.h in -I/home/vibflysleep/gpu-camera-sample/OtherLibsLinux/GenICam/library/CPP/include
Check if you installed GenICamTM Package Version 2019.11 in right way (see Readme.md).

- Download GenICamTM Package Version 2019.11 (https://www.emva.org/wp-content/uploads/GenICam_Package_2019.11.zip).
- Unpack it to a temporary folder and cd to Reference Implementation folder.
- Create <ProjectRoot>/OtherLibsLinux/GenICam folder.
- Unpack GenICam_V3_2_0-Linux64_x64_gcc48-Runtime.tgz or GenICam_V3_2_0-Linux64_ARM_gcc49-Runtime.tgz into <ProjectRoot>/OtherLibsLinux/GenICam folder.
- Unpack GenICam_V3_2_0-Linux64_x64_gcc48-SDK.tgz or GenICam_V3_2_0-Linux64_ARM_gcc49-SDK.tgz into <ProjectRoot>/OtherLibsLinux/GenICam/library/CPP
- Ensure Qt uses gcc, not clang to build project.

**Comment by antortjim** [comment]
Thank you for your quick reply!

I now made sure I placed the GenICam files you mention exactly as supposed to:

```
cd ~/gpu-camera-sample/OtherLibsLinux/GenICam
tree -L 4
.
├── bin
│   ├── CLProtocol
│   │   └── Test
│   │       └── Linux64_x64
│   └── Linux64_x64
│       ├── libCLAllSerial_gcc48_v3_2.so
│       ├── libCLProtocol_gcc48_v3_2.so
│       ├── libFirmwareUpdate_gcc48_v3_2.so
│       ├── libGCBase_gcc48_v3_2.so
│       ├── libGenApi_gcc48_v3_2.so
│       ├── liblog4cpp_gcc48_v3_2.so
│       ├── libLog_gcc48_v3_2.so
│       ├── libMathParser_gcc48_v3_2.so
│       ├── libNodeMapData_gcc48_v3_2.so
│       └── libXmlParser_gcc48_v3_2.so
├── library
│   └── CPP
│       └── include
│           ├── Base
│           ├── CLProtocol
│           ├── FirmwareUpdate
│           ├── GenApi
│           ├── GenCP
│           ├── GenICamFwd.h
│           ├── GenICam.h
│           ├── _GenICamVersion.h
│           ├── GenICamVersion.h
│           ├── Log
│           └── log4cpp
├── License_ReadMe.txt
├── licenses
│   ├── CLSerAll_LICENSE.txt
│   ├── GenICam_License_20180629.pdf
│   ├── LGPL.txt
│   ├── MIT_License.txt
│   ├── pcre2_License.txt
│   ├── xs3p_License.mht
│   └── xxhash_License.txt
└── log
    └── config-unix
        └── DefaultLogging.properties

18 directories, 23 files

```

I have also disabled the ClangCodeModel following this answer
https://stackoverflow.com/a/58737644/3541756

![image](https://user-images.githubusercontent.com/13869571/155182148-7336aac1-b214-4db9-8bf8-63d75eddf9c9.png)

is that what you meant?

I still get one error at Build time:
```
g++ -c -pipe -g -Wall -W -D_REENTRANT -fPIC -DSUPPORT_GENICAM -DGENICAM_NO_AUTO_IMPLIB -DGENTL_INSTALL_PATH='"/opt/XIMEA/lib"' -DQT_QML_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../src/CameraSample -I. -I/usr/local/cuda-11/include -I../../OtherLibsLinux/nvcodecs/include -I../../OtherLibsLinux/FastvideoSDK/fastvideo_sdk/inc -I../../OtherLibsLinux/FastvideoSDK -I../../OtherLibsLinux/FastvideoSDK/common -I/home/vibflysleep/gpu-camera-sample/OtherLibsLinux/FastvideoSDK/libs/OpenGL/inc -I/home/vibflysleep/gpu-camera-sample/OtherLibsLinux/ffmpeg/include -I../../OtherLibsLinux/GenICam/library/CPP/include -I../../OtherLibsLinux/FastvideoSDK/core_samples -I../../src/CameraSample -I../../src/CameraSample/CUDASupport -I../../src/CameraSample/Widgets -I../../src/CameraSample/Camera -I../../src/CameraSample/RtspServer -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtOpenGL -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o MJPEGEncoder.o ../../src/CameraSample/MJPEGEncoder.cpp
```

```
In file included from ../../src/CameraSample/Camera/GeniCamCamera.h:12,
                 from ../../src/CameraSample/MainWindow.cpp:59:
../../src/CameraSample/rc_genicam_api/pixel_formats.h:42:10: fatal error: GenTL/PFNC.h: No such file or directory
   42 | #include <GenTL/PFNC.h>
      |          ^~~~~~~~~~~~~~
```
please see log
[build.log](https://github.com/fastvideo/gpu-camera-sample/files/8118674/build.log)

If I then click on build again, I get 12 errors, the one from before plus GenICam.h not being found several times
[build2.log](https://github.com/fastvideo/gpu-camera-sample/files/8118728/build2.log)

**Comment by AlexVRom** [comment]
Sorry, thera are 2 more header files you need to copy from GenICam archive.
Create OtherLibsLinux\GenICam\library\CPP\include\GenTL folder
Copy there 
GenICam_Package_2019.11.zip\GenICam_Package_2019.11\GenTL\GenTL_v1_6.zip\GenTL.h
GenICam_Package_2019.11.zip\GenICam_Package_2019.11\SFNC\PFNC.h

This would fix the issue.
We will put it into Readme.md

**Comment by antortjim** [comment]
Dear @AlexVRom 

I confirm that indeed solves the building problems. After building, I clicked Run and I could successfully get the live feed from a Flir camera (`Chameleon3 CM3-U3-13Y3C`).

But trying to connect to `Basler a2A3840-45umPRO` did not work out and I get the following error
```
Error occured:
fastRawUnpackerDecode failed
Code: 9 (FAST_INVALID_SIZE)
```

![image](https://user-images.githubusercontent.com/13869571/155285895-d44e88e6-36bd-4dfc-9740-610796647bfb.png)


Would that be an easy fix? Thank you so much!

**Comment by fastvideo** [comment]
We have tested our SDK with NVIDIA GeForce RTX 3070/3080 with G104 architecture. We haven't tested it with GeForce RTX 3080TI and 3090 which are based on G102 architecture. So I would suggest testing the software on another GPU.

If it's working with FLIR, but is not working with Basler, it could be a problem with unpacking. Please send us your RAW frame (packed image) for evaluation.

**Comment by AlexVRom** [comment]
Could you set
bool Globals::gEnableLog = true;
in Globals.cpp, line 35, run application and send log file from application directory?
