### ISSUE TITLE
 ‘JPEG_420’ was not declared in this scope

### ISSUE THREAD

**Issue by qizhouqiqi** [fastvideo/gpu-camera-sample#13]
Dear fastvideo,
thanks for developing the program!
Specs:
Xavier  Ubuntu 18.04
CUDA 10.0
qtcreator 5.9.5
Since the CUDA version of Xavier I use is 10.0, I use GPU camera sample version v0 0.1.1.
When I built this project, Six errors occurred. I want to know whether there is a problem with this version of the code, whether it can be successfully built, or whether there is a problem with my environment configuration I don't know how to solve them. I want to ask you for help.
ERROR1:
/home/xavier1/gpu-camera-sample-0.0.1.1/src/CUDASupport/CUDAProcessorOptions.h:94: error: ‘JPEG_420’ was not declared in this scope
         JpegSamplingFmt = JPEG_420;
ERROR2:
/home/xavier1/gpu-camera-sample-0.0.1.1/src/Camera/FrameBuffer.h:40: error: wrong number of template arguments (2, should be 1)
 typedef Image<unsigned char, FastAllocator> ImageT;
ERROR3:
/home/xavier1/gpu-camera-sample-0.0.1.1/src/Camera/FrameBuffer.h:40: error: ‘typedef int ImageT’ redeclared as different kind of symbol
 typedef Image<unsigned char, FastAllocator> ImageT;
ERROR4:
/home/xavier1/gpu-camera-sample-0.0.1.1/src/Camera/FrameBuffer.h:52: error: invalid use of template-name ‘ImageT’ without an argument list
     ImageT* getLastImage();
ERROR5:
/home/xavier1/gpu-camera-sample-0.0.1.1/src/Camera/FrameBuffer.h:74: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T> class QVector’
     QVector<ImageT> mImages;
ERROR6:
/home/xavier1/gpu-camera-sample-0.0.1.1/src/CUDASupport/CUDAProcessorBase.h:86: error: ‘ImageT’ is not a type
     virtual fastStatus_t Transform(ImageT *image, CUDAProcessorOptions& opts);

**Comment by AlexVRom** [comment]
Some time ago we changed  JPEG_420 and other jpeg related constants with FAST_ prefix ( JPEG_420 -> FAST_ JPEG_420 and so on). You should change them in your source code or upgrade Fastvideo SDK to newer version.

**Comment by qizhouqiqi** [comment]
Thanks for your help!
I have another problem. I successfully run the demo. I loaded the Bayer PGM file in the IMG folderBecause I don't have a suitable camera. but I didn't see the speed of JPEG encoding and decoding on the demo. The attachment contains a screenshot of the results of running the demo. I want to know how to see the speed of JPEG encoding and decoding.
I want to know the encoding and decoding speed of images and videos, but if there is no suitable camera, how should I know the encoding and decoding speed?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fastvideo/gpu-camera-sample"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 凌晨1:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fastvideo/gpu-camera-sample]  ‘JPEG_420’ was not declared in this scope (Issue #13)





 
Some time ago we changed  JPEG_420 and other jpeg related constants with FAST_ prefix ( JPEG_420 -&gt; FAST_ JPEG_420 and so on). You should change them in your source code or upgrade Fastvideo SDK to newer version.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fastvideo** [comment]
Please run JpegSample application to get these benchmarks. You can find that application in the /bin folder of Fastvideo SDK.
