### ISSUE TITLE
how to test JPEG encode and decode

### ISSUE THREAD

**Issue by qizhouqiqi** [fastvideo/gpu-camera-sample#14]
I successfully run the demo. I loaded the Bayer PGM file in the IMG folderBecause I don't have a suitable camera. but I didn't see the speed of JPEG encoding and decoding on the demo. Following are screenshots of the results of running the demo. I want to know how to see the speed of JPEG encoding and decoding.
I want to know the encoding and decoding speed of images and videos, but if there is no suitable camera, how should I know the encoding and decoding speed?
[https://s2.loli.net/2022/03/08/CgmU1pXz4fy5GNH.png](url)
[https://s2.loli.net/2022/03/08/Q47Tu5KisGaN1nY.png](url)

**Comment by fastvideo** [comment]
In that application we don't show the speed of JPEG encoding and decoding. Here you can see GPU time which shows total time of image processing on the GPU.
To get the speed of JPEG encoding and decoding please download our demo SDK and run JpegSample applications to get benchmarks you need. Please bear in mind that to get max performance for JPEG decoding, your jpg image needs to have restart markers. Without markers the performance will be low.
