### ISSUE TITLE
Demo  couldn't  work well

### ISSUE THREAD

**Issue by LosReturn** [fastvideo/gpu-camera-sample#17]
Hi, the Demo of Window SDK only shows the error  'Unknown statement' (I am trying to use DFPD). What happened?  my env is : RTX2060 with cuda 11.2

**Comment by fastvideo** [comment]
It means one of the following:
1. You don't have NVIDIA GPU at your PC (we don't support AMD and Intel GPUs).
2. NVIDIA driver is not installed. Please install the latest NVIDIA driver.

**Comment by fastvideo** [comment]
Please bear in mind that this SDK is compatible with CUDA-11.4, not with CUDA-11.2
