### ISSUE TITLE
(Jetson-Xavier, ximea-camera) cmake --build ->no memory allocation

### ISSUE THREAD

**Issue by Randy37773** [fastvideo/gpu-camera-sample#18]
After compiling the app (cmake --build .), the app starts, but no memory is allocated and no images are processed. 
I collected hopefully useful information [here](https://github.com/Randy37773/jetson-xavier-misc/tree/main/gpu-camera/fastvideo/log-version-20220916). 

* Ximea driver are installed (xiCamTooll is working as default user)
* a pre compiled version of GPUCameraSample works as default user[logs](https://github.com/Randy37773/jetson-xavier-misc/blob/main/gpu-camera/fastvideo/log-version-20220916/developStart202210030110.txt)
* compiling my own version (after installing requirements, compiling ffmpeg from source), doing ccmake (configure, generate, build) succeeds (some warnings)
* the application starts [log](https://github.com/Randy37773/jetson-xavier-misc/blob/main/gpu-camera/fastvideo/log-version-20220916/startlog202210030105.txt), but in the benchmark-window no processing is shown [allocated 0 MB](https://github.com/Randy37773/jetson-xavier-misc/blob/main/gpu-camera/fastvideo/log-version-20220916/NoMemoryAllocation-01.png)
[CMakeLists.txt](https://github.com/fastvideo/gpu-camera-sample/files/9695351/CMakeLists.txt)
[developStart202210030110.txt](https://github.com/fastvideo/gpu-camera-sample/files/9695352/developStart202210030110.txt)
[gpu-camera-sample-dir.txt](https://github.com/fastvideo/gpu-camera-sample/files/9695353/gpu-camera-sample-dir.txt)
<img width="757" alt="gpu-camera-sample--stdout-001" src="https://user-images.githubusercontent.com/95871582/193520037-b3cee7df-a196-4263-9cb6-d4fec55d3bc4.png">
<img width="187" alt="NoMemoryAllocation-01" src="https://user-images.githubusercontent.com/95871582/193520042-de85a7d2-8e5a-4334-87ae-ef639bf70a44.png">
[startlog202210030105.txt](https://github.com/fastvideo/gpu-camera-sample/files/9695354/startlog202210030105.txt)
[CMakeCache.txt](https://github.com/fastvideo/gpu-camera-sample/files/9695355/CMakeCache.txt)

**Comment by AlexVRom** [comment]
Have you compiled application for GenICam or for XIAPI (DEFINES += SUPPORT_XIMEA or DEFINES += SUPPORT_GENICAM)?

**Comment by AlexVRom** [comment]
Could you compile it with qmake?

**Comment by Randy37773** [comment]
> Have you compiled application for GenICam or for XIAPI (DEFINES += SUPPORT_XIMEA or DEFINES += SUPPORT_GENICAM)?


In cmake I found  USE_XIMEA, XIMEA_INC and XIMEA_LIB:

//ON
USE_XIMEA:BOOL=ON

//Path to a library.
V4L2_LIB:FILEPATH=/usr/lib/aarch64-linux-gnu/tegra/libv4l2.so.0

//Path to a file.
Ximea_INC:PATH=/opt/XIMEA/include

//Path to a library.
Ximea_LIB:FILEPATH=/usr/lib/libm3api.so

**Comment by Randy37773** [comment]
> Could you compile it with qmake?


editing common_defs.pri
-> DEFINES += SUPPORT_XIMEA

running: make clean
running:  qmake
running: make

no change in behaviour

**Comment by artthirt** [comment]
Hi. Have you downloaded the latest fastvideo sdk libraries from README.md? This behavior may be due to the fact that the trial period has expired.
Seems also you running the app from the console without X11 display. This app need running in the gnome/kde desktop environment.

**Comment by Randy37773** [comment]
> Hi. Have you downloaded the latest fastvideo sdk libraries from README.md? This behavior may be due to the fact that the trial period has expired. Seems also you running the app from the console without X11 display. This app need running in the gnome/kde desktop environment.

Yes, I 
* downloaded the [this](https://drive.google.com/file/d/1HgfqboijA8VlQAulEm69a7ayx-hQVxuO/view?usp=sharing)
* copied the files into lib/Arm64 (should this be recursive?)
* made links: ´./make_links.sh ~/gpu-camera-sample/OtherLibsLinux/FastvideoSDK/fastvideo_sdk/lib/Linux64´  
* edited common_prefs.pri
* sadly "building the project" is the point with no information whatsoever
  doing ´make clean´, ´qmake´, ´make´ does not give a GPUCameraSample, ist just gives a ´CameraSample´ which starts (GUI works), but ?memor-allocation? shows up to be `0`.
* complete ´ls -alsR´ output is [here](https://github.com/Randy37773/jetson-xavier-misc/blob/main/gpu-camera/fastvideo/log-version-20220916/gpu-camera-sample-dir.txt)

I am working remote via ssh x11-forwarding. this works fine, as I can use lxterminal, xiCamTool and the pre-compiles GPUCameraSample. I do not mind to see a live-camera image. For now it would be very nice, to get the self-compiled app to behave like the pre-compiled one (in order to modify it).


`
./gpu-camera-sample/OtherLibsLinux/FastvideoSDK/fastvideo_sdk/lib/Arm64:
libfastvideo_decoder_j2k.so.7.0.0.1.0170601
libfastvideo_denoise.so -> libfastvideo_denoise.so.2
libfastvideo_encoder_j2k.so.3.1.0.0.0170601
libfastvideo_j2kFfmpegWrapper.so.1.0.0.0.0170601
libfastvideo_j2kFfmpegWrapper.so.2 -> libfastvideo_j2kFfmpegWrapper.so.1.0.0.0.0170601
libfastvideo_jpegCpuDecoder.so.1.0.0.0.0170601
libfastvideo_mjpeg.so.1.0.0.0.0170601
libfastvideo_nppFilter.so.1.0.1.1.0170601
libfastvideo_nppFilter.so.2 -> libfastvideo_nppFilter.so.1.0.1.1.0170601
libfastvideo_nppGeometry.so.1.1.0.0.0170601
libfastvideo_nppGeometry.so.2 -> libfastvideo_nppGeometry.so.1.1.0.0.0170601
libfastvideo_nppResize.so.1.0.1.0.0170601
libfastvideo_nppResize.so.2 -> libfastvideo_nppResize.so.1.0.1.0.0170601
libfastvideo_nppRotate.so.1.0.1.0.0170601
libfastvideo_nppRotate.so.2 -> libfastvideo_nppRotate.so.1.0.1.0.0170601
libfastvideo_sdk.so -> libfastvideo_sdk.so.18
libfastvideo_sdk.so.0.17.6.1.0170601
libfastvideo_sdk.so.18 -> libfastvideo_sdk.so.0.17.6.1.0170601
make_sl.sh
`

**Comment by artthirt** [comment]
Maybe this is the problem. No one has tested this application in this mode. As I can see the opengl context cannot be created. Maybe this is why the app is not working.

**Comment by Randy37773** [comment]
> Maybe this is the problem. No one has tested this application in this mode. As I can see the opengl context cannot be created. Maybe this is why the app is not working.

I *can use* the precompiled (better the compiled version of you in /home/nvidia/develop/) in my remote setup. So to me this does not seem to be the problem. 
Even in *your* /home/nvidia/develop/ version I can not reproduce to compile the GPUCameraSample binary. I always get the CameraSample binary which starts, but shows allocation of zero.
That was the reason, I cloned the repository and went through all steps again (three times alread) and got the very same result: a CameraSample binary, which shows allocation of 0.

(*your* means: fastvideo connected to this very same machine and developed an unpacker for my ximea camera. this model was not supported till then. the repo now includes this (cpu)unpacker. so i cloned the repo into a separate directory in order to get a clean start ... failing).)

**Comment by artthirt** [comment]
[https://user-images.githubusercontent.com/95871582/193520037-b3cee7df-a196-4263-9cb6-d4fec55d3bc4.png](https://user-images.githubusercontent.com/95871582/193520037-b3cee7df-a196-4263-9cb6-d4fec55d3bc4.png)

As you can see now the app using opengl context. Seems x11-forwarding cannot using opengl. Because of that the app fails. For work in this mode need to rebuild the app without opengl widget or create the console app without gui.

**Comment by Randy37773** [comment]
> https://user-images.githubusercontent.com/95871582/193520037-b3cee7df-a196-4263-9cb6-d4fec55d3bc4.png
> As you can see now the app using opengl context. Seems x11-forwarding cannot using opengl. Because of that the app fails. For work in this mode need to rebuild the app without opengl widget or create the console app without gui.

"the console app without gui"? I maybe overlooked that. Can you  provide a link? 
Please do not mention ...FastvideoSDK/fastvideo_samples/Camera(Multi)Sample because these examples are not helpfull in this case (no camera nowhere). 

**I can use** your compiled version with x11-forwarding, as you can see in [this logs](https://github.com/Randy37773/jetson-xavier-misc/blob/main/gpu-camera/fastvideo/log-version-20220916/developStart202210030110.txt)  _as long as I need no live-pic_ as you can see in this [screenshot](https://github.com/Randy37773/jetson-xavier-misc/blob/main/gpu-camera/fastvideo/log-version-20220916/GPUCameraSample-develop-X11FORWARDING.png).

Whatsoever, here ist a [screenshot](https://github.com/Randy37773/jetson-xavier-misc/blob/main/gpu-camera/fastvideo/log-version-20220916/screenshot-self-compiled-directyOnGNOME.png) which shows the very same behaviour directly on the javier-machine (no x11-forwarding). As you can see, this is the same failure.

I can use your compiled version in /home/nvidia/develop/  in x11-forwarding.
All I want to do is, to **reproduce** your compilation in order to get a binary with the same functions.

**Comment by artthirt** [comment]
These are my steps to compile the app:

git clone https://github.com/fastvideo/gpu-camera-sample.git
cd gpu-camera-sample/
#vi src/common_defs.pri
#uncomment DEFINES += SUPPORT_XIMEA # before this need to install XIMEA SDK
#download fastvideosdk for arm64
mkdir -p OtherLibsLinux/FastvideoSDK
cd OtherLibsLinux/FastvideoSDK
tar -xf \<path-to-fastvideo-sdk\> 
cd fastvideo_sdk/lib/
chmod +x make_sl.sh 
./make_sl.sh
cd ../../../../
mkdir build
cd build
qmake ../src/GPUCameraSample.pro 
make -j6 #number of threads
cd ../GPUCameraSample_Arm64/release/
cp ../../OtherLibsLinux/FastvideoSDK/fastvideo_sdk/lib/libfastvideo_sdk.so.18 .
export LD_LIBRARY_PATH=.
sudo tee /sys/module/usbcore/parameters/usbfs_memory_mb >/dev/null <<<0
./GPUCameraSample
