### ISSUE TITLE
 fastvideo_sdk.h: No such file or directory

### ISSUE THREAD

**Issue by locdoan12121997** [fastvideo/gpu-camera-sample#2]
![image](https://user-images.githubusercontent.com/18070388/80202339-a7901f00-864f-11ea-88a9-1794ee9036ac.png)
I have try added external library to qtcreater through its project settings, but still not work

**Comment by AlexVRom** [comment]
fastvideo_sdk.h and other SDK headers should be placed into  gpu-camera-sample/OtherLibsLinux/FastvideoSDK/fastvideo_sdk/inc
see  gpu-camera-sample/src/common_unix.pri  for details

**Comment by AlexVRom** [comment]
> I have try added external library to qtcreater through its project settings, but still not work

You should add additional include directory for headers

**Comment by locdoan12121997** [comment]
So, i manage to get through this error by adding this line to additional arguments for the qmake build steps
```
INCLUDEPATH+=/home/aioz-loc/working/gpu-camera-sample/OtherLibsLinux/fastvideoSDK/fastvideo_sdk/inc INCLUDEPATH+=/home/aioz-loc/working/gpu-camera-sample/OtherLibsLinux/fastvideoSDK/core_samples INCLUDEPATH+=/home/aioz-loc/working/gpu-camera-sample/OtherLibsLinux/fastvideoSDK/common
```
