### ISSUE TITLE
JPEG2000

### ISSUE THREAD

**Issue by sdreamforchen** [fastvideo/gpu-camera-sample#20]
Hello，the"JPEG2000 encoder and decoder on GPU for camera applications" in road map, where is the source code.
 Thanks a lot.

**Comment by fastvideo** [comment]
That feature (JPEG2000 encoder and decoder on GPU) exists in the Fastvideo SDK, though it wasn't implemented in the gpu-camera-sample project yet. Right now you can use JPEG encoding on GPU instead, it's very fast. It's difficult to say when it could be added to the project.
