### ISSUE TITLE
  Input  Maximum image memory

### ISSUE THREAD

**Issue by liuhongyan123456** [fastvideo/gpu-camera-sample#21]
Hello, would like to ask us this J2KEncoders algorithm can handle the largest image, I have a tens of megabytes of 8bits single-band gray map, using J2KEncoder compression results damaged。

**Comment by fastvideo** [comment]
The task of J2K encoding could be solved with Fastvideo SDK, not with that application, which is intended for cameras.
You can download demo SDK from that site or send us request to info@fastcompression.com 
What are your target OS and GPU model?
Please also send us your sample images for evaluation.
