### ISSUE TITLE
CUDAProcessorBase.cpp:93: error: ‘fastRawImportFromDeviceDestroy’ was not declared in this scope

### ISSUE THREAD

**Issue by locdoan12121997** [fastvideo/gpu-camera-sample#3]
![image](https://user-images.githubusercontent.com/18070388/80345679-b36c2300-8893-11ea-8c0f-95bfd0b1d6b0.png)
Hi it's me in the issue #2 . After managing to pass the library and header linking error, I got these errors while building the project:
‘fastRawImportFromDeviceDestroy’ was not declared in this scope
'struct fastBitDepthConverter_t' has no member named 'targetBitsPerChannel'
'struct fastBitDepthConverter_t' has no member named 'isOverrideSourceBitsPerChannel'

**Comment by locdoan12121997** [comment]
For the struct error, changing struct to this may have fixed it
```
typedef struct {
        unsigned targetBitsPerChannel;
        bool isOverrideSourceBitsPerChannel;
} fastBitDepthConverter_t;
```
However, dont know how to fix the other error.

**Comment by AlexVRom** [comment]
Looks like source code uses newer Fastvideo SDK version. 
We'll check out what version is uploaded and update it if needed.
What SDK version you are using?

**Comment by locdoan12121997** [comment]
the fast sdk version is 0.15.0.0

**Comment by AlexVRom** [comment]
Try this for Ubuntu:
https://drive.google.com/open?id=1ZQ8fWYRKTuvLbF3mhkJFc2pSz7kkLk_m

and this one for ARM
https://drive.google.com/open?id=1AsvMlnp-SpIEsxzkg3WpR--mzCPDw6mi

We will update links to version 15.3 tomorrow

**Comment by locdoan12121997** [comment]
Thanks, this gets me through the error but creates more path error, I think i'll post another issue
