### ISSUE TITLE
gpu-camera-sample/src/RtspPlayer/cuviddecoder/cuviddecoder.cpp:3: error: cuviddec.h: No such file or directory

### ISSUE THREAD

**Issue by locdoan12121997** [fastvideo/gpu-camera-sample#4]
![image](https://user-images.githubusercontent.com/18070388/80462998-bcc3c100-8961-11ea-9d55-c502e058e2c7.png)
Hello, I have this undetected library error. I have find the file in my whole system using
```
sudo find / -name cuviddec.h
```
But still no find to be found. I I comment the line, i'll get a lot of error.

**Comment by artthirt** [comment]
Need to copy and unpack this archive to the directory "OtherLibsLinux" for ubuntu (OtherLibs for windows)
[nvcodecs.zip](https://github.com/fastvideo/gpu-camera-sample/files/4544431/nvcodecs.zip)

That headers and libraries moved from this sdk: https://developer.nvidia.com/nvidia-video-codec-sdk/download

**Comment by artthirt** [comment]
Also for start apps need to create symbolic links from libfastvideo_sdk.so and libfastvideo_densoise.so:
libfastvideo_sdk.so.18 and libfastvideo_densoise.so.2
