### ISSUE TITLE
ERROR: failed checking for nvcc

### ISSUE THREAD

**Issue by rupei110** [fastvideo/gpu-camera-sample#5]
I follow the build_ffmpeg.sh to build ffmpeg on jetson AGX Xavier.
But the ./configure got error
![image](https://user-images.githubusercontent.com/50095586/111588807-ff52ee00-87fe-11eb-8628-994f481f4de9.png)
The cuda10.0 is already installed
![image](https://user-images.githubusercontent.com/50095586/111588917-25788e00-87ff-11eb-917b-1c41508d93f7.png)

**Comment by fastvideo** [comment]
Could you please send us your "ffbuild/config.log" file to check the issue?

**Comment by rupei110** [comment]
[config.log](https://github.com/fastvideo/gpu-camera-sample/files/6186609/config.log)

**Comment by rupei110** [comment]
> Could you please send us your "ffbuild/config.log" file to check the issue?

Here is the config.log, Thank you
[config.log](https://github.com/fastvideo/gpu-camera-sample/files/6186614/config.log)

**Comment by AlexVRom** [comment]
According to your log file, script is trying to compile with nvcc following code
extern "C" {
    __global__ void hello(unsigned char *data) {}
}
It compiles it with the following command line:
nvcc -gencode arch=compute_30,code=sm_30 -O2 -m64 -ptx -c -o /tmp/ffconf.DozItaTn/test.o /tmp/ffconf.DozItaTn/test.cu

/tmp/ffconf.DozItaTn/test.cu - is a file name, created by script.

nvcc was failed to compile this file and configure script stopped at that point with the message failed to check nvcc. It doesn't mean script cannot find nvcc. It means that nvcc cannot compile code with arch=compute_30,code=sm_30.

Btw, according to your log, you are using CUDA 10.0. GPU camera sample application uses Fastvideo SDK, that compiled with CUDA 10.2, so you will have to install CUDA 10.2 to compile application even if you successfully compile ffmpeg.

**Comment by AlexVRom** [comment]
We also installed latest firmware with CUDA 10.2 on our Xavier and we don't have any problem compiling ffmpeg with build_ffmpeg.sh script out of the box.

**Comment by seajayshore** [comment]
I also have the same issue trying to compile on Jetson Nano.

![Screenshot](https://user-images.githubusercontent.com/20320545/124164898-232dfd00-da99-11eb-9cbf-5400097959c6.png)

Here is my [config.log](https://github.com/fastvideo/gpu-camera-sample/files/6749845/config.log) file

I have CUDA 10.2 installed. Any help would be appreciated!

**Comment by AlexVRom** [comment]
What ffmpeg version are you trying to compile?
Do you have nvcc in path? What happens if you type nvcc in console?
Also what is console output from the following commands:
nvcc -gencode arch=compute_30,code=sm_30 -O2 -std=c++11 -m64 -ptx
nvcc -gencode arch=compute_60,code=sm_60 -O2 -std=c++11 -m64 -ptx
