### ISSUE TITLE
Cannot open Ximea camera feed

### ISSUE THREAD

**Issue by seajayshore** [fastvideo/gpu-camera-sample#6]
I've managed to compile & run with the `SUPPORT_XIMEA` define uncommented in common_defs.pri so that I can connect to my Ximea camera

The app launches fine but when I click the "open camera" button the video feed that appears is black (see screenshot) and I receive a `QObject::connect: No such signal` error from `CameraSetupWidget.cpp `

The camera model is MX031CG-SY from the xiC series (USB-3.1).
I'm using Qt 5.15.2 with MSVC2019 compiler. 

Is this a Ximea/camera error or a Qt/UI error?

**Error message:**
```
QCoreApplication::applicationDirPath: Please instantiate the QApplication object first
---- xiOpenDevice API:V4.18.02.00 started ----
EAL_IF_xiFAPI_Top::InitializeDevice sn:CECAU2019026 name:MC031CG-SY-UB
FGTL_SetParam_to_CAL error from CAL: -1015, addr:x27317e
XiApiToGentlParamModel Auto bandwidth measurement finished (396MBps). Safe limit set to: 317MBps
---- Device opened. Model:MC031CG-SY-UB SN:CECAU2019026 FwF1:01.31 API:V4.18.02.00 ----
xiFAPI_Device::AcquisitionStop - ignored: acquisition is not running
Initialising CUDAProcessorBase...
Created fastRawUnpackerCreate, free mem	5277106176
Created hDeviceToHostRawAdapter, free mem	5268520960
Created SAM, free mem	5242961920
Created hSamMux, free mem	5242961920
Created hLinearizationLut, free mem	5236539392
Created hDeviceToHostLinRawAdapter, free mem	5230116864
Created hWhiteBalance, free mem	5223694336
Created BPC, free mem	5210914816
Created hBpcMux, free mem	5210914816
Created hDebayer, free mem	5185159168
Created hDenoise, free mem	5099110400
Created hDenoiseMux, free mem	5099110400
Created hOutLut, free mem	5079908352
Created hDeviceToHost16Adapter, free mem	5060771840
Created h16to8Transform, free mem	5051203584
Created hDeviceToHostAdapter, free mem	5041635328
Created hExportToDevice, free mem	5032067072
Created hGLBuffer, free mem	5022498816
Created hMjpegEncoder, free mem	4938416128
hMjpegEncoder allocated 78 MBytes
QObject::connect: No such signal XimeaCamera::stateChanged(CameraBase::cmrCameraState) in ..\..\src\CameraSample\Widgets\CameraSetupWidget.cpp:63
QObject::connect:  (receiver name: 'cameraController')
xiFAPI_Device::AllocateBuffers Allocating buffers. Count:28 OneBuff:4669 KiB All:128 MiB Frm:x10c0053
xiAPI error: Expected XI_OK in:..\API\xiFAPI\camera_model\XiApiToGentlParamModel.cpp XiApiToGentlParamModel::GetHDR/Line:608
DEF_GetBufferInfo Warning: not implemented infoCmd:1004
```

**Screenshot:**
![2021-05-11 (1)](https://user-images.githubusercontent.com/20320545/117844964-0aaf1c80-b278-11eb-8b95-ced4b91fe609.png)

**Comment by fastvideo** [comment]
Please set Frame rate 30 fps or 60 fps at Camera settings. Currently you are trying to work at 10.000 fps.

**Comment by fastvideo** [comment]
You can also check your XIMEA camera with CamTool application which could be downloaded from XIMEA's site.

**Comment by seajayshore** [comment]
I've tried to change the values in the Camera settings UI after opening the camera. It allows me to change the Frame Rate to 30 however the Exposure Time cannot be changed from the very large default value when I run the app which is perhaps why output is not working?
I tried to change the values in the Camera Settings UI before opening the camera and it doesn't allow me.

I confirm that the camera is working OK in XIMEA CamTool and I can set both Frame rate to 30FPS & Exposure Time to something sensible like 30ms. 

Perhaps I can reset the default values from the UI somehow?

**Comment by seajayshore** [comment]
With some debug code I noticed the program never progressed to the `on_spnFrameRate_valueChanged()` or `on_spnFrameRate_valueChanged` functions in `CameraSetupWidget.cpp`

So I investigated the "QObject::connect: No such signal" error further and found, I think, that SIGNAL & SLOT lines 65 & 66 in `CameraSetupWidget.cpp` should be set to `GPUCameraBase::cmrCameraState` not `CameraBase::cmrCameraState`.

The app still does not display the video and the Exposure Time is still not being set in the UI as described above but now it reaches the debug code I added in `on_spnFrameRate_valueChanged()` or `on_spnFrameRate_valueChanged` at least.

**Comment by AlexVRom** [comment]
We fixed QObject::connect error. Also check CameraSetupWidget::setCamera procedure with debugger and see if you get correct values of exposure time and frame rate from camera.

**Comment by seajayshore** [comment]
Thanks for the suggestions, I dug into the `setCamera `& `XimeaCamera::open` functions and found none of the `xiGetParam` or `xiSetParam` functions were actually working properly. From that I have managed to solve the problem now! :-) 

I had to manually replace the xiapi64.dll file in the build folder with the newest version from Ximea. 
I had previously added these newer files to the OtherLibs folder (overwriting the older ones provided in the pre-compiled OtherLibs folder on your README page) and I expected Qt to just update them in the build folder once I rebuilt the app - but that doesn't happen apparently (I'm new to Qt).

So previously the app was using Ximea API v4.18.02.00 and failing to communicate with my newer xiC camera. 
Now it's on v4.22.00.00 and working perfectly. :-)

Perhaps you could update the OtherLibs folder in the README for future users?
Also heads-up that you changed the `common_defs.pri` code in the previous commit so that Ximea cameras are enabled by default which maybe you didn't mean to do as default?
