### ISSUE TITLE
Arm64 Installation Error

### ISSUE THREAD

**Issue by SofoklisKat** [fastvideo/gpu-camera-sample#9]
I tried to install the project in Jetson Nano and Jetson AGX xavier with only the GeniCam option and  encountered the following error:

gpu-camera-sample/OtherLibsLinux/FastvideoSDK/fastvideo_sdk/lib/Arm64/libfastvideo_sdk.so: file not recognized: File format not recognized

Any ideas ?

**Comment by AlexVRom** [comment]
Have you built it from source or used prebuilt binaries?

**Comment by SofoklisKat** [comment]
Both had the same error. 
Find the solution
